[general]
llm = "AzureOpenAI" # you only need to configure the llm you want to use
max_translation_attempts = 6

[AzureOpenAI]
api_key = "your-api-key"
endpoint = "https://your-endpoint.openai.azure.com/"
api_version = "2024-12-26" # change this to your own API version
model = "gpt-4o" # change this to your own model

[OpenAI]
api_key = "your-api-key"
model = "gpt-4o" # change this to your own model
